spring:
  application: kotlin-hexagon
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:public;MODE=MYSQL;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS PUBLIC
#    username: sa
#    password: sa
    url: jdbc:postgresql://localhost:5432/kotlin-hexagon
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  banner:
    location: banner.txt

  flyway:
    enabled: true
    locations: classpath/migrations
    schemas: PUBLIC

javax:
  persistence:
    schema-generation:
      database:
        action: drop-and-create

