version: '3.8'
services:
  hexagon-root:
    image: hexagon-root
    build:
      context: ./
    ports:
      - "8081:8080"
    depends_on:
      - "db"
    volumes:
      - /data/hexagon-root
  db:
    container_name: pg_container
    image: postgres:14-bullseye
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hexagon_db
    ports:
      - "5432:5432"
    volumes:
      - /data/pg_db
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - "db"
    volumes:
      - /data/pg_admin
  prometheus:
    container_name: prometheus
    image: "prom/prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana
    image: "grafana/grafana"
    ports:
      - "3000:3000"
