version: '3.8'
services:
  hexagon-root:
    image: hexagon-root
    restart: on-failure
    build:
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    volumes:
      - /data/hexagon-root
  db:
    container_name: pg_container
    image: postgres:14-bullseye
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hexagon_db
    ports:
      - "5432:5432"
    volumes:
      - /data/pg_db
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - "db"
    volumes:
      - /data/pg_admin
  prometheus:
    container_name: prometheus
    image: "prom/prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana
    image: "grafana/grafana"
    ports:
      - "3000:3000"
  elasticsearch:
    image: elasticsearch:8.7.0
    container_name: elasticsearch
    restart: on-failure
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
      xpack.security.enabled: true
      xpack.security.enrollment.enabled: true
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk
  logstash:
    image: logstash:8.7.0
    container_name: logstash
    restart: on-failure
    volumes:
      - ./logstash.conf/:/usr/share/logstash.conf
      - ./logstash.yml/:/usr/share/logstash.yml
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
  kibana:
    image: kibana:8.7.0
    container_name: kibana
    restart: on-failure
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

