spring:
  application: kotlin-hexagon
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:postgresql://db:5432/hexagon_db
    username: root
    password: root

  banner:
    location: banner.txt

  flyway:
    enabled: true
    locations: classpath/migrations
    schemas: PUBLIC

  h2:
    console:
      enabled: true
      path: /h2-console

javax:
  persistence:
    schema-generation:
      database:
        action: drop-and-create

axon:
  serializer:
    general: jackson
  axonserver:
    servers: localhost:8124
